package proyecto.alfa.pkg1;

/**
 *
 * @author Diego
 */
public class Ingresar extends javax.swing.JInternalFrame {
    static int auxId;
    int i;
    public Ingresar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreDeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setTitle("Ingresar");
        setLayer(3);
        setVisible(true);

        jLabel1.setText("Nombre de usuario:");

        jLabel2.setText("Contraseña:");

        botonIngresar.setText("Ingresar");
        botonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(nombreDeUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonIngresar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(120, 90, 320, 145);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseClicked
        if(Administrador.administrador.nombreDeUsuario.equals(nombreDeUsuario.getText()) && Administrador.administrador.contraseña.equals(contraseña.getText())){
            Principal.usuario.setText(Administrador.administrador.nombreDeUsuario);
            Principal.BaseDeDatosMenu.setEnabled(true);
            Principal.ventanaIngresar.setVisible(false);
            Principal.cerrarSesion.setEnabled(true);
            Principal.IngresarMenu.setEnabled(false);
        }
        for(i = 0; i < Usuario.listaDeUsuarios.length; i++){
        if(Usuario.listaDeUsuarios[i].nombreDeUsuario.equals(nombreDeUsuario.getText()) && Usuario.listaDeUsuarios[i].contraseña.equals(contraseña.getText())){
            auxId = i;
            Principal.usuario.setText(Usuario.listaDeUsuarios[i].nombreDeUsuario);
            Principal.CatalogoDeProductosMenu.setEnabled(true);
            Principal.ventanaIngresar.setVisible(false);
            Principal.cerrarSesion.setEnabled(true);
            Catalogo.añadirArticulo.setEnabled(true);
            Catalogo.pagar.setEnabled(true);
            Principal.jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/alfa/pkg1/appletIcon(1).gif")));
            Principal.IngresarMenu.setEnabled(false);
            Principal.estadoDeCuenta.setEnabled(true);
            EstadoDeCuenta.actualizarEstado();
            break;
        }
        }
    }//GEN-LAST:event_botonIngresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    public javax.swing.JTextField contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField nombreDeUsuario;
    // End of variables declaration//GEN-END:variables
}
