package proyecto.alfa.pkg1;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diego
 */
public class Principal extends javax.swing.JFrame {
    static Ingresar ventanaIngresar = new Ingresar();
    Catalogo ventanaCatalogo = new Catalogo();
    BaseDeDatosClientes ventanaClientes = new BaseDeDatosClientes();
    BaseDeDatosInventario ventanaInventario = new BaseDeDatosInventario();
    VentanaCuentas ventanaCuentas = new VentanaCuentas();
    EstadoDeCuenta ventanaEstadoDeCuenta = new EstadoDeCuenta();
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();
        cuenta1 = new javax.swing.JRadioButton();
        cuenta2 = new javax.swing.JRadioButton();
        estadoDeCuenta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        IngresarMenu = new javax.swing.JMenu();
        BaseDeDatosMenu = new javax.swing.JMenu();
        ClientesSubmenu = new javax.swing.JMenuItem();
        InventarioSubmenu = new javax.swing.JMenuItem();
        CatalogoDeProductosMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de ventas");

        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setDesktopManager(null);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usuario.setText("Usuario");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/alfa/pkg1/DukeWave.gif"))); // NOI18N
        jLabel1.setText("           ");
        jLabel1.setMaximumSize(new java.awt.Dimension(55, 55));
        jLabel1.setMinimumSize(new java.awt.Dimension(55, 55));

        cerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        cerrarSesion.setText("Cerrar sesión");
        cerrarSesion.setEnabled(false);
        cerrarSesion.setMargin(new java.awt.Insets(2, 2, 2, 2));
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        buttonGroup1.add(cuenta1);
        cuenta1.setSelected(true);
        cuenta1.setText("Cuenta1");

        buttonGroup1.add(cuenta2);
        cuenta2.setText("Cuenta 2");

        estadoDeCuenta.setText("Estado de cuenta");
        estadoDeCuenta.setEnabled(false);
        estadoDeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoDeCuentaActionPerformed(evt);
            }
        });

        jButton2.setText("Desactivar cuenta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cuenta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estadoDeCuenta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cuenta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrarSesion)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuenta1)
                            .addComponent(estadoDeCuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(cuenta2)))))
        );

        IngresarMenu.setText("Ingresar");
        IngresarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(IngresarMenu);

        BaseDeDatosMenu.setText("Bases de datos");
        BaseDeDatosMenu.setEnabled(false);

        ClientesSubmenu.setText("Clientes");
        ClientesSubmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesSubmenuActionPerformed(evt);
            }
        });
        BaseDeDatosMenu.add(ClientesSubmenu);

        InventarioSubmenu.setText("Inventario");
        InventarioSubmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioSubmenuActionPerformed(evt);
            }
        });
        BaseDeDatosMenu.add(InventarioSubmenu);

        jMenuBar1.add(BaseDeDatosMenu);

        CatalogoDeProductosMenu.setText("Catálogo de productos");
        CatalogoDeProductosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatalogoDeProductosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(CatalogoDeProductosMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        setBounds(100, 100, 600, 475);
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMenuMouseClicked
        try{
        jDesktopPane1.add(ventanaIngresar);
        }catch(IllegalArgumentException ex){
        }
        ventanaIngresar.setVisible(true);
    }//GEN-LAST:event_IngresarMenuMouseClicked

    private void ClientesSubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesSubmenuActionPerformed
        try{
        jDesktopPane1.add(ventanaClientes);
        }catch(IllegalArgumentException ex){
            
        }
        ventanaClientes.setVisible(true);
    }//GEN-LAST:event_ClientesSubmenuActionPerformed

    private void InventarioSubmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioSubmenuActionPerformed
        try{
        jDesktopPane1.add(ventanaInventario);
        }catch(IllegalArgumentException ex){
            
        }
        ventanaInventario.setVisible(true);
    }//GEN-LAST:event_InventarioSubmenuActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        usuario.setText("Usuario");
        ventanaCatalogo.setVisible(false);
        ventanaClientes.setVisible(false);
        ventanaInventario.setVisible(false);
        ventanaIngresar.setVisible(true);
        ventanaIngresar.nombreDeUsuario.setText("");
        ventanaIngresar.contraseña.setText("");
        cerrarSesion.setEnabled(false);
        IngresarMenu.setEnabled(true);
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void CatalogoDeProductosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatalogoDeProductosMenuMouseClicked
        try{
        jDesktopPane1.add(ventanaCatalogo);
        }catch(IllegalArgumentException ex){       
        }
        ventanaCatalogo.setVisible(true);
        try {
            ventanaCatalogo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CatalogoDeProductosMenuMouseClicked

    private void estadoDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoDeCuentaActionPerformed
        try{
        jDesktopPane1.add(ventanaEstadoDeCuenta);
        }catch(IllegalArgumentException ex){
            
        }
        ventanaEstadoDeCuenta.setVisible(true);
    }//GEN-LAST:event_estadoDeCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu BaseDeDatosMenu;
    public static javax.swing.JMenu CatalogoDeProductosMenu;
    private javax.swing.JMenuItem ClientesSubmenu;
    public static javax.swing.JMenu IngresarMenu;
    private javax.swing.JMenuItem InventarioSubmenu;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JButton cerrarSesion;
    public static javax.swing.JRadioButton cuenta1;
    public static javax.swing.JRadioButton cuenta2;
    public static javax.swing.JButton estadoDeCuenta;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}